{{- if and .Values.tls.enabled .Values.tls.certs.selfSigner.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "selfcerts.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
      {{- include "insignis.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ include "selfcerts.fullname" . }}-cleaner
      labels:
        {{- include "insignis.labels" . | nindent 8 }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: cleaner
          image: "{{ .Values.tls.selfSigner.image.registry }}/{{ .Values.tls.selfSigner.image.repository }}:{{ .Values.tls.selfSigner.image.tag }}"
          imagePullPolicy: "{{ .Values.tls.selfSigner.image.pullPolicy }}"
          args:
            - cleanup
            - --namespace={{ .Release.Namespace }}
          env:
          # cleanup command deletes secrets with these names
          # ${STATEFULSET_NAME}-client-secret
          # ${STATEFULSET_NAME}-node-secret
          # ${STATEFULSET_NAME}-ca-secret
          - name: STATEFULSET_NAME
            value: {{ .Values.database.user }}
      serviceAccountName: {{ include "rotatecerts.fullname" . }}
{{- end}}