kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ template "insignis.fullname" . }}-budget
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "insignis.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "insignis.selectorLabels" . | nindent 6 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  maxUnavailable: {{ .Values.deployment.budget.maxUnavailable | int64 }}