{{- if .Values.tls.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "insignis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "insignis.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    {{- if or .Values.tls.certs.provided .Values.tls.certs.certManager }}
    verbs: ["get"]
    {{- else }}
    verbs: ["create", "get"]
{{- end }}