{{- if and .Values.tls.enabled .Values.tls.certs.selfSigner.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rotatecerts.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "insignis.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rotatecerts.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rotatecerts.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}