apiVersion: v1
kind: Service
metadata:
  name: {{ include "insignis.fullname" . }}
  labels:
    {{- include "insignis.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http":"HTTPS"}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "insignis.selectorLabels" . | nindent 4 }}
  {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}