{{- if and .Values.tls.enabled .Values.tls.certs.selfSigner.enabled }}
  {{ template "cockroachdb.tls.certs.selfSigner.validation" . }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "rotatecerts.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "insignis.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}